[phases.setup]
nixPkgs = ["nodejs-18_x", "npm"]
cmds = ["npm ci --legacy-peer-deps"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
SKIP_ENV_VALIDATION = "true"