[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x", "bash"]

[phases.build]
cmds = ["bash scripts/railway-build.sh"]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
SKIP_ENV_VALIDATION = "true"